#! /usr/bin/env python
"""Draw every figure the documentation uses, and write it to ``docs/images``.

The figures are not decoration: each one is the argument for a paragraph, and a
figure generated before a behaviour changed shows the reader the old behaviour
with the new text beside it. So they are generated by running the code, and this
is what runs it -- rather than a procedure someone carried out by hand once and
has to remember.

The scenes live in OpenGLContext, which is where the renderer is; this package
generates geometry and has no OpenGL in it. So this script needs OpenGLContext
and a GL driver, finds the demo scripts beside it in the workspace, and says so
plainly when it cannot::

    python tools/capture_figures.py                 # regenerate every figure
    python tools/capture_figures.py lathe caps      # just these
    python tools/capture_figures.py --check         # is anything stale?
    python tools/capture_figures.py --list

``--check`` draws everything into a temporary directory and compares, without
touching ``docs/images``. It is the question "would regenerating change
anything", which is what a release wants answered.

Each figure is drawn in its own process: a GL context is not something to set up
twice in one interpreter, and a crash in one figure should cost that figure
rather than the run.
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

#: Every figure the documentation refers to, as
#: ``output name -> (demo script, figure argument or None)``. The names are the
#: files in ``docs/images``; the scripts are OpenGLContext's.
FIGURES: dict[str, tuple[str, str | None]] = {
    'shapes': ('extrusions_shapes.py', None),
    'joins': ('extrusions_joins.py', None),
    'normals': ('extrusions_normals.py', None),
    'curves': ('extrusions_curves.py', None),
    'tessellation': ('extrusions_tessellation.py', None),
    'vrml97': ('extrusions_vrml97.py', None),
    'fig_preprocessing': ('extrusions_preprocessing.py', None),
    'fig_texture_modes': ('extrusions_gallery.py', 'texture_modes'),
    'fig_texture_parameter': ('extrusions_gallery.py', 'texture_parameter'),
    'fig_texture_caps': ('extrusions_gallery.py', 'texture_caps'),
    'fig_curve_sampling': ('extrusions_gallery.py', 'curve_sampling'),
    'fig_lathe': ('extrusions_gallery.py', 'lathe'),
    'fig_spiral': ('extrusions_gallery.py', 'spiral'),
    'fig_screw': ('extrusions_gallery.py', 'screw'),
    'fig_polycone': ('extrusions_gallery.py', 'polycone'),
    'fig_caps': ('extrusions_gallery.py', 'caps'),
    'fig_contours': ('extrusions_gallery.py', 'contours'),
    'fig_scale_twist': ('extrusions_gallery.py', 'scale_twist'),
}

#: Where the figures go, relative to this file.
IMAGES = Path(__file__).resolve().parent.parent / 'docs' / 'images'

#: Frames drawn before the capture is taken. The scene is static, so this is
#: only about giving texture uploads and shader compilation a chance to finish.
FRAMES = 12

#: The window is square because the figures are, and larger than the file so the
#: result is downsampled -- which is the cheapest antialiasing there is.
CAPTURE_SIZE = 900
OUTPUT_SIZE = 300

#: What the demo module is expected to call its context class.
CONTEXT_ATTRIBUTE = 'TestContext'

#: Run the demo module without letting it start its own main loop, then start
#: one at the size we want. Written to a file rather than passed with `-c` so a
#: traceback from it has line numbers that mean something.
BOOTSTRAP = """\
import importlib.util, os, sys
script, figure = sys.argv[1], sys.argv[2]
sys.argv = [script] + ([figure] if figure else [])
sys.path.insert(0, os.path.dirname(os.path.abspath(script)))
spec = importlib.util.spec_from_file_location('_figure_demo', script)
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)          # __name__ is not __main__, so it waits
from OpenGLContext.contextdefinition import ContextDefinition
size = int(os.environ['CAPTURE_FIGURE_SIZE'])
context = getattr(module, %r)
context.ContextMainLoop(definition=ContextDefinition(size=(size, size)))
""" % (CONTEXT_ATTRIBUTE,)


class CaptureError(RuntimeError):
    """A figure could not be drawn, with the reason a reader can act on."""


def find_demos() -> Path:
    """OpenGLContext's ``tests`` directory, or a complaint saying where to look."""
    override = os.environ.get('OPENGLCONTEXT_TESTS')
    candidates = [Path(override)] if override else []
    here = Path(__file__).resolve().parent.parent
    candidates += [here.parent / 'openglcontext' / 'tests', here.parent / 'tests']
    for candidate in candidates:
        if (candidate / 'extrusions_gallery.py').exists():
            return candidate
    raise CaptureError(
        "cannot find OpenGLContext's tests directory, which is where the demo "
        'scenes live. Looked in: %s. Set OPENGLCONTEXT_TESTS to point at it.'
        % ', '.join(str(c) for c in candidates)
    )


def is_blank(path: Path) -> bool:
    """Whether the capture came out with nothing in it.

    A figure that draws nothing is the failure this script exists to catch: it
    costs nothing to notice here and is easy to miss in a directory listing.
    """
    from PIL import Image

    with Image.open(path) as handle:
        return handle.convert('L').getextrema()[1] <= 2


def capture(name: str, demos: Path, into: Path, bootstrap: Path) -> Path:
    """Draw one figure, returning where it was written."""
    script, figure = FIGURES[name]
    source = demos / script
    if not source.exists():
        raise CaptureError('%s does not exist' % source)
    environment = dict(
        os.environ,
        # A mapped surface makes SwapBuffers wait for a compositor that is not
        # going to answer, so the window stays hidden and renders offscreen.
        OPENGLCONTEXT_HIDDEN='1',
        # Core profile, which is the path these figures are documenting: a
        # generated mesh reaches the GPU as a `PBRMesh` drawn by a shader. The
        # fixed-function pipeline is kept for the demos and tests that exercise
        # it deliberately, and draws no `PBRMesh` at all -- so a figure captured
        # under it comes out black rather than wrong, which is worse.
        OPENGLCONTEXT_PROFILE=os.environ.get('OPENGLCONTEXT_PROFILE', 'core'),
        # Core profile wants GLFW: it is the backend that creates one.
        OPENGLCONTEXT_BACKEND=os.environ.get('OPENGLCONTEXT_BACKEND', 'glfw'),
        OPENGLCONTEXT_AUTO_EXIT_FRAMES=str(FRAMES),
        OPENGLCONTEXT_AUTO_EXIT_CAPTURE_DIR=str(into),
        OPENGLCONTEXT_AUTO_EXIT_CAPTURE_NAME=name,
        CAPTURE_FIGURE_SIZE=str(CAPTURE_SIZE),
    )
    finished = subprocess.run(
        [sys.executable, str(bootstrap), str(source), figure or ''],
        env=environment,
        capture_output=True,
        text=True,
        timeout=600,
        check=False,
    )
    written = into / ('%s.png' % name)
    if finished.returncode != 0:
        raise CaptureError(
            'drawing %s exited %d:\n%s' % (name, finished.returncode, finished.stderr[-2000:])
        )
    if not written.exists():
        raise CaptureError('drawing %s wrote no image:\n%s' % (name, finished.stderr[-2000:]))
    if is_blank(written):
        raise CaptureError(
            '%s came out blank. The geometry may be fine and the scene not '
            'drawing it -- check the demo scene rather than the generator.' % name
        )
    _downsample(written)
    return written


def _downsample(path: Path) -> None:
    from PIL import Image

    with Image.open(path) as handle:
        if handle.size == (OUTPUT_SIZE, OUTPUT_SIZE):
            return
        handle.convert('RGB').resize((OUTPUT_SIZE, OUTPUT_SIZE), Image.LANCZOS).save(
            path, optimize=True
        )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument('names', nargs='*', help='figures to draw; omit for all')
    parser.add_argument('--list', action='store_true', help='name every figure and its scene')
    parser.add_argument(
        '--check',
        action='store_true',
        help='draw into a temporary directory and report what differs, '
        'without writing to docs/images',
    )
    parser.add_argument(
        '--out', type=Path, default=IMAGES, help='where to write (default docs/images)'
    )
    arguments = parser.parse_args(argv)

    if arguments.list:
        for name in sorted(FIGURES):
            script, figure = FIGURES[name]
            print('%-24s %s %s' % (name, script, figure or ''))
        return 0

    names = arguments.names or list(FIGURES)
    unknown = [n for n in names if n not in FIGURES]
    if unknown:
        parser.error('unknown figure(s): %s; try --list' % ', '.join(unknown))

    try:
        demos = find_demos()
    except CaptureError as error:
        print('error: %s' % error, file=sys.stderr)
        return 2

    destination = Path(tempfile.mkdtemp(prefix='figures-')) if arguments.check else arguments.out
    destination.mkdir(parents=True, exist_ok=True)
    bootstrap_dir = Path(tempfile.mkdtemp(prefix='figure-bootstrap-'))
    bootstrap = bootstrap_dir / 'bootstrap.py'
    bootstrap.write_text(BOOTSTRAP, encoding='utf-8')

    failed, changed = [], []
    try:
        for name in names:
            try:
                written = capture(name, demos, destination, bootstrap)
            except CaptureError as error:
                failed.append(name)
                print('FAILED  %-24s %s' % (name, error), file=sys.stderr)
                continue
            if arguments.check:
                existing = arguments.out / ('%s.png' % name)
                same = existing.exists() and existing.read_bytes() == written.read_bytes()
                if not same:
                    changed.append(name)
                print('%-7s %s' % ('same' if same else 'DIFFERS', name))
            else:
                print('wrote   %s' % written)
    finally:
        shutil.rmtree(bootstrap_dir, ignore_errors=True)
        if arguments.check:
            shutil.rmtree(destination, ignore_errors=True)

    if failed:
        print(
            '\n%d figure(s) could not be drawn: %s' % (len(failed), ', '.join(failed)),
            file=sys.stderr,
        )
    if arguments.check and changed:
        print('\n%d figure(s) would change: %s' % (len(changed), ', '.join(changed)))
    return 1 if failed else 0


if __name__ == '__main__':  # pragma: no cover - a command line entry point
    raise SystemExit(main())
